# -*- coding: utf-8 -*-
MODEL:
  META_ARCHITECTURE: "OpenVocabularyRCNN"
  RESNETS:
    OUT_FEATURES: ["res4"]
  TEACHER_CLOUD:
    META_ARCHITECTURE: 'GLIP'
    PROCESSOR_ARCHITECTURE: 'GLIP_PROCESSOR'
    COLLECT_ARCHITECTURE: 'GLIP_COLLECTOR'
    TYPE: 'GLIP_Swin_L' # swinB or swinT
    CONFIG_PATH: './configs/GLIP/glip_Swin_L.yaml'
    WEIGHT: './cloud_models/glip_large_model.pth'
  TEACHER_OFFLINE:
    META_ARCHITECTURE: 'CLIP'
    TEXT_ENCODER: "CLIP_TEXT"
    COLLECT_ARCHITECTURE: 'CLIP_COLLECTOR'
  BACKBONE:
    NAME: "build_clip_image_backbone"
  MASK_ON: False
  WEIGHTS: ''
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512]]
  #   ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  PROPOSAL_GENERATOR:
    NAME: "DualTeacherRPN"
  RPN:
  #   POSITIVE_FRACTION: 0.25
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    IN_FEATURES: ["res4"]
  ROI_HEADS:
    NAME: "OpenVocabularyRes5ROIHeads"
    TEACHER_OFFLINE: "CLIPRes5ROIHeads"
    POOLING_TYPE: 'meanpool'
    IN_FEATURES: ['res4']
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14 # set 14, because res5 has downsampling.
    CLS_AGNOSTIC_BBOX_REG: True
CLOUD:
  Trainer: "CoinTrainer"
  OFFLINE_TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE_OFFLINE: 0.9996
  PROTOTYPE_UPDATE_WEIGHT: 0.9996
  ADD_PROMPT_NUM: 4
  BG_TRAIN: True
  UPDATE_BACKBONE: True
  LOSS_TYPE: 'MILCrossEntropy' # MILCrossEntropy or MILFocalLoss
INPUT:
  FORMAT: "RGB"
  TEACHER_CLOUD:
    COLLECT_AUG: ""  # options: "" "ZOOM&AUG" "ZOOM" "AUG". We use "" by default. Only used during pretraining
    MIN_SIZE_TEST: 600 # keep the same with faster rcnn
  MIN_SIZE_TRAIN: (600,)
  MIN_SIZE_TEST: 600
DATALOADER:
  NUM_WORKERS: 2
VERSION: 2
