# -*- coding: utf-8 -*-
_BASE_: "./Base-GDINO-CLASSONLY.yaml"
MODEL:
  TEACHER_CLOUD:
    TEST_THRESHOLD: 0.25
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN_UNLABEL: ("foggytrain_0.02",)
  TEST: ("foggyval_0.02",)
TEST:
  EVALUATOR: "VOCeval"

OUTPUT_DIR: "./output/foggy/"