# -*- coding: utf-8 -*-
_BASE_: "../Base-CLIP.yaml"
MODEL:
  TEACHER_OFFLINE:
    TYPE: "RN101"
  RESNETS:
    DEPTH: 101
  TEACHER_CLOUD:
    TEST_THRESHOLD: 0.25
CLOUD:
  UPDATE_BACKBONE: False
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  STYLE_NAME: 'clipart style'
  TRAIN_UNLABEL: ("cliparttrain",)
  TEST: ("clipartval",)
TEST:
  EVALUATOR: "VOCeval"

OUTPUT_DIR: "./output/clipart/"