# -*- coding: utf-8 -*-
_BASE_: "../Base-CLIP-GLIP.yaml"
MODEL:
  TEACHER_OFFLINE:
    TYPE: "RN50"
  RESNETS:
    DEPTH: 50
  TEACHER_CLOUD:
    TEST_THRESHOLD: 0.5
CLOUD:
  UPDATE_BACKBONE: False
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  STYLE_NAME: 'foggy cityscapes style'
  TRAIN_UNLABEL: ("foggytrain_0.02",)
  TEST: ("foggyval_0.02",)
TEST:
  EVALUATOR: "VOCeval"

OUTPUT_DIR: "./output/foggy/"