# -*- coding: utf-8 -*-
_BASE_: "../Base-CLIP.yaml"
MODEL:
  TEACHER_OFFLINE:
    TYPE: "RN50"
  RESNETS:
    DEPTH: 50
  TEACHER_CLOUD:
    TEST_THRESHOLD: 0.25
CLOUD:
  UPDATE_BACKBONE: False
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  STYLE_NAME: 'cityscapes style'
  TRAIN_UNLABEL: ("citytrain",)
  TEST: ("cityval",)
TEST:
  EVALUATOR: "VOCeval"

OUTPUT_DIR: "./output/cityscape/"