# -*- coding: utf-8 -*-
_BASE_: "../Base-GDINO.yaml"
MODEL:
  TEACHER_CLOUD:
    TEST_THRESHOLD: 0.25
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TRAIN_UNLABEL: ("SIMtrainval_car",)
  TEST: ("SIMtrainval_car",)
TEST:
  EVALUATOR: "VOCeval"

OUTPUT_DIR: "./output/SIM/"