# -*- coding: utf-8 -*-
_BASE_: "../Base-ORACLE.yaml"
MODEL:
  TEACHER_OFFLINE:
    TYPE: "RN50"
  RESNETS:
    DEPTH: 50
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (50000, 70000)
  FACTOR_LIST: (1, 0.5, 0.1)
  MAX_ITER: 90000
  IMS_PER_BATCH: 3
  BASE_LR: 0.001
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 1000
  PER_MODULE_PARAM_WEIGHT: 
    [{'backbone.encoder.visual': 0.1, 'backbone.encoder.visual.layer4': 0.1, 
    'backbone.encoder.attnpool': 0.1, 'embedding_tmp': 1.0, 'add_in_embedding': 1.0, 'logit_scale': 0.0,
    'anchor_generator': 1.0 }]
DATASETS:
  STYLE_NAME: 'BDD100K style'
  TRAIN: ("BDD100Ktrain",)
  TEST: ("BDD100Kval",)
INPUT:
  RANDOM_FLIP: "horizontal"
CLOUD:
  UPDATE_BACKBONE: True
  ADD_PROMPT_NUM: 4
  
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "VOCeval"
OUTPUT_DIR: "./output/BDD100K/oracle"
VIS_PERIOD: 0
SEED: 2024